//! Framebuffer text console with a cell grid, 16 colors and a visible
//! cursor. It implements the Linux console's terminal type (`TERM=linux`):
//! the capabilities its terminfo entry lists, such as scroll regions, line
//! insertion and deletion, the DEC line-drawing set, insert mode and the
//! palette sequences, so that full-screen curses programs (htop) work.

use bootloader_api::info::{FrameBuffer, FrameBufferInfo, PixelFormat};
use core::fmt;
use noto_sans_mono_bitmap::{get_raster, get_raster_width, FontWeight, RasterHeight};
use crate::sync::IrqSpinLock;
use x86_64::instructions::interrupts::without_interrupts;

const FONT_WEIGHT: FontWeight = FontWeight::Regular;
const RASTER_HEIGHT: RasterHeight = RasterHeight::Size24;
const CHAR_WIDTH: usize = get_raster_width(FONT_WEIGHT, RASTER_HEIGHT);
const LINE_HEIGHT: usize = RASTER_HEIGHT.val() + 2;
const MAX_COLS: usize = 256;
const MAX_ROWS: usize = 128;
const MAX_PARAMS: usize = 8;

/// ANSI color order: black, red, green, yellow, blue, magenta, cyan, white,
/// then the bright variants.
const PALETTE: [(u8, u8, u8); 16] = [
    (0, 0, 0),
    (170, 0, 0),
    (0, 170, 0),
    (170, 85, 0),
    (0, 0, 170),
    (170, 0, 170),
    (0, 170, 170),
    (170, 170, 170),
    (85, 85, 85),
    (255, 85, 85),
    (85, 255, 85),
    (255, 255, 85),
    (85, 85, 255),
    (255, 85, 255),
    (85, 255, 255),
    (255, 255, 255),
];
const DEFAULT_FG: u8 = 7;

include!(concat!(env!("OUT_DIR"), "/logo.rs"));
/// The boot logo as RGB pixels, generated by build.rs from assets/logo.png.
static LOGO: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/logo.rgb"));
const DEFAULT_BG: u8 = 0;

#[derive(Clone, Copy, PartialEq)]
struct Cell {
    ch: char,
    fg: u8,
    bg: u8,
    underline: bool,
}

const BLANK: Cell = Cell { ch: ' ', fg: DEFAULT_FG, bg: DEFAULT_BG, underline: false };

/// The DEC special graphics set (VT100 line drawing) for the characters
/// that select it, as the terminfo `acsc` string of the Linux console maps
/// them.
fn dec_graphics(ch: char) -> char {
    match ch {
        '`' => '◆',
        'a' => '▒',
        'f' => '°',
        'g' => '±',
        'h' => '░',
        'i' => '§',
        'j' => '┘',
        'k' => '┐',
        'l' => '┌',
        'm' => '└',
        'n' => '┼',
        'o' => '⎺',
        'p' => '⎻',
        'q' => '─',
        'r' => '⎼',
        's' => '⎽',
        't' => '├',
        'u' => '┤',
        'v' => '┴',
        'w' => '┬',
        'x' => '│',
        'y' => '≤',
        'z' => '≥',
        '{' => 'π',
        '|' => '≠',
        '}' => '£',
        '~' => '·',
        '0' => '█',
        '+' => '→',
        ',' => '←',
        '-' => '↑',
        '.' => '↓',
        c => c,
    }
}

/// The console starts before the heap exists, so the cell grid is static.
static mut CELLS: [[Cell; MAX_COLS]; MAX_ROWS] = [[BLANK; MAX_COLS]; MAX_ROWS];

#[derive(PartialEq)]
enum Parse {
    Normal,
    Escape,
    Csi,
    /// ESC ( or ESC ): the next byte designates the G0 or G1 character set.
    Charset(u8),
    /// ESC ] P: seven hex digits redefine a palette entry (Linux).
    Palette,
    /// Any other operating system command, up to BEL or ESC \.
    Osc,
}

pub struct Console {
    fb: &'static mut [u8],
    info: FrameBufferInfo,
    cells: &'static mut [[Cell; MAX_COLS]; MAX_ROWS],
    cols: usize,
    rows: usize,
    col: usize,
    row: usize,
    /// Set after writing the last column; the wrap happens on the next char.
    wrap_pending: bool,
    fg: u8,
    bg: u8,
    bold: bool,
    reverse: bool,
    saved: (usize, usize),
    cursor_visible: bool,
    cursor_drawn: Option<(usize, usize)>,
    parse: Parse,
    params: [u16; MAX_PARAMS],
    nparams: usize,
    private: bool,
    utf8: [u8; 4],
    utf8_len: usize,
    utf8_need: usize,
    reply: [u8; REPLY_CAP],
    reply_len: usize,
    /// Scroll region, first and last row (inclusive).
    top: usize,
    bottom: usize,
    /// G0/G1 designate the line-drawing set; SO selects G1, SI G0.
    g0_graphics: bool,
    g1_graphics: bool,
    shift_out: bool,
    underline: bool,
    insert_mode: bool,
    autowrap: bool,
    palette: [(u8, u8, u8); 16],
    /// ESC ] P digits collected so far.
    osc: [u8; 7],
    osc_len: usize,
    /// The palette changed: the next row to redraw (redraws run in pieces,
    /// see `write_some`).
    redraw_next: Option<usize>,
    /// Cells drawn during the current lock hold.
    work: usize,
}

/// Cells drawn per lock hold (well under a millisecond on hardware, a few
/// under emulation): drawing runs with interrupts off, so `write_bytes`
/// gives the lock and interrupts back whenever this much is done. Nobody
/// waits long for the console and no timer tick is lost, however much a
/// program writes.
const WORK_BUDGET: usize = 64;
/// The budget an answer to a query takes (see `push_reply`).
const REPLY_WORK: usize = 16;
/// Room for the answers of one lock hold: at most `WORK_BUDGET / REPLY_WORK` of
/// them, each at most 16 bytes ("\x1b[rrrr;ccccR").
const REPLY_CAP: usize = (WORK_BUDGET / REPLY_WORK) * 16;

impl Console {
    fn put_pixel(&mut self, x: usize, y: usize, (r, g, b): (u8, u8, u8)) {
        let color = match self.info.pixel_format {
            PixelFormat::Rgb => [r, g, b, 0],
            PixelFormat::Bgr => [b, g, r, 0],
            _ => [((r as u16 + g as u16 + b as u16) / 3) as u8, 0, 0, 0],
        };
        let bpp = self.info.bytes_per_pixel;
        let off = (y * self.info.stride + x) * bpp;
        self.fb[off..off + bpp].copy_from_slice(&color[..bpp]);
    }

    fn draw_cell(&mut self, col: usize, row: usize, invert: bool) {
        self.work += 1;
        let cell = self.cells[row][col];
        let (mut fg, mut bg) = (self.palette[cell.fg as usize], self.palette[cell.bg as usize]);
        if invert {
            core::mem::swap(&mut fg, &mut bg);
        }
        let special = super::glyphs::is_special(cell.ch);
        let raster = if special {
            None
        } else {
            Some(
                get_raster(cell.ch, FONT_WEIGHT, RASTER_HEIGHT)
                    .or_else(|| get_raster('?', FONT_WEIGHT, RASTER_HEIGHT))
                    .expect("font lacks '?'"),
            )
        };
        let glyph = raster.as_ref().map(|r| r.raster());
        let (x0, y0) = (col * CHAR_WIDTH, row * LINE_HEIGHT);
        for dy in 0..LINE_HEIGHT {
            let underline_row = cell.underline && dy == LINE_HEIGHT - 3;
            for dx in 0..CHAR_WIDTH {
                let a = if underline_row {
                    255
                } else if let Some(glyph) = glyph {
                    glyph.get(dy).and_then(|l| l.get(dx)).copied().unwrap_or(0) as u16
                } else {
                    super::glyphs::coverage(cell.ch, dx, dy, CHAR_WIDTH, LINE_HEIGHT).unwrap_or(0) as u16
                };
                let mix = |f: u8, b: u8| ((f as u16 * a + b as u16 * (255 - a)) / 255) as u8;
                self.put_pixel(x0 + dx, y0 + dy, (mix(fg.0, bg.0), mix(fg.1, bg.1), mix(fg.2, bg.2)));
            }
        }
    }

    fn set_cell(&mut self, col: usize, row: usize, cell: Cell) {
        self.cells[row][col] = cell;
        self.draw_cell(col, row, false);
    }

    fn blank(&self) -> Cell {
        Cell { ch: ' ', fg: DEFAULT_FG, bg: self.bg, underline: false }
    }

    fn hide_cursor(&mut self) {
        if let Some((c, r)) = self.cursor_drawn.take() {
            self.draw_cell(c, r, false);
        }
    }

    fn show_cursor(&mut self) {
        if self.cursor_visible {
            let pos = (self.col.min(self.cols - 1), self.row);
            self.draw_cell(pos.0, pos.1, true);
            self.cursor_drawn = Some(pos);
        }
    }

    /// Moves rows `first..=last` up by `n` (text and pixels); the rows that
    /// open up at the bottom are blank.
    fn scroll_up(&mut self, first: usize, last: usize, n: usize) {
        if first > last || last >= self.rows {
            return;
        }
        let n = n.min(last - first + 1);
        let line = LINE_HEIGHT * self.info.stride * self.info.bytes_per_pixel;
        self.fb.copy_within((first + n) * line..(last + 1) * line, first * line);
        for r in first..=last - n {
            self.cells[r] = self.cells[r + n];
        }
        let blank = self.blank();
        for r in last + 1 - n..=last {
            for c in 0..self.cols {
                self.set_cell(c, r, blank);
            }
        }
    }

    /// Moves rows `first..=last` down by `n`; blank rows open up at the top.
    fn scroll_down(&mut self, first: usize, last: usize, n: usize) {
        if first > last || last >= self.rows {
            return;
        }
        let n = n.min(last - first + 1);
        let line = LINE_HEIGHT * self.info.stride * self.info.bytes_per_pixel;
        self.fb.copy_within(first * line..(last + 1 - n) * line, (first + n) * line);
        for r in (first + n..=last).rev() {
            self.cells[r] = self.cells[r - n];
        }
        let blank = self.blank();
        for r in first..first + n {
            for c in 0..self.cols {
                self.set_cell(c, r, blank);
            }
        }
    }

    /// Line feed (index): at the bottom of the scroll region the region
    /// scrolls; below it the cursor just moves until the last row.
    fn line_feed(&mut self) {
        if self.row == self.bottom {
            self.scroll_up(self.top, self.bottom, 1);
        } else if self.row + 1 < self.rows {
            self.row += 1;
        }
    }

    /// Reverse index (ESC M): the mirror image of `line_feed`.
    fn reverse_index(&mut self) {
        if self.row == self.top {
            self.scroll_down(self.top, self.bottom, 1);
        } else if self.row > 0 {
            self.row -= 1;
        }
    }

    fn put_char(&mut self, ch: char) {
        if self.wrap_pending && self.autowrap {
            self.wrap_pending = false;
            self.col = 0;
            self.line_feed();
        }
        let graphics = if self.shift_out { self.g1_graphics } else { self.g0_graphics };
        let ch = if graphics { dec_graphics(ch) } else { ch };
        let mut fg = if self.bold && self.fg < 8 { self.fg + 8 } else { self.fg };
        let mut bg = self.bg;
        if self.reverse {
            core::mem::swap(&mut fg, &mut bg);
        }
        if self.insert_mode {
            for c in (self.col + 1..self.cols).rev() {
                let src = self.cells[self.row][c - 1];
                self.set_cell(c, self.row, src);
            }
        }
        self.set_cell(self.col, self.row, Cell { ch, fg, bg, underline: self.underline });
        if self.col + 1 >= self.cols {
            self.wrap_pending = true;
        } else {
            self.col += 1;
        }
    }

    fn erase(&mut self, row: usize, from: usize, to: usize) {
        let blank = self.blank();
        for c in from..to.min(self.cols) {
            self.set_cell(c, row, blank);
        }
    }

    fn move_to(&mut self, col: usize, row: usize) {
        self.col = col.min(self.cols - 1);
        self.row = row.min(self.rows - 1);
        self.wrap_pending = false;
    }

    /// Draws the boot logo centered above the first text row and moves the
    /// cursor below it. The logo is only pixels: it scrolls away with the
    /// text and disappears when its rows are redrawn.
    fn draw_logo(&mut self) {
        const MARGIN: usize = 16;
        let rows = (LOGO_HEIGHT + 2 * MARGIN).div_ceil(LINE_HEIGHT);
        if LOGO_WIDTH > self.info.width || rows >= self.rows {
            return;
        }
        let x0 = (self.info.width - LOGO_WIDTH) / 2;
        for (y, line) in LOGO.chunks_exact(LOGO_WIDTH * 3).enumerate() {
            for (x, p) in line.chunks_exact(3).enumerate() {
                self.put_pixel(x0 + x, MARGIN + y, (p[0], p[1], p[2]));
            }
        }
        self.move_to(0, rows);
    }

    pub fn clear_screen(&mut self) {
        for r in 0..self.rows {
            self.erase(r, 0, self.cols);
        }
        self.move_to(0, 0);
    }

    fn param(&self, i: usize, default: u16) -> usize {
        match self.params.get(i) {
            Some(&p) if i < self.nparams && p != 0 => p as usize,
            _ => default as usize,
        }
    }

    /// An answer to a query (a cursor position report, device attributes). Each
    /// counts as `REPLY_WORK` of the lock hold's budget, so one hold makes at most
    /// `WORK_BUDGET / REPLY_WORK` of them, which `reply` always holds: the writer
    /// takes them before the lock goes (`write_with_replies`), none is lost.
    fn push_reply(&mut self, bytes: &[u8]) {
        self.work += REPLY_WORK;
        let n = bytes.len().min(self.reply.len() - self.reply_len);
        self.reply[self.reply_len..self.reply_len + n].copy_from_slice(&bytes[..n]);
        self.reply_len += n;
    }

    fn sgr(&mut self) {
        let count = self.nparams.max(1);
        for i in 0..count {
            let p = if i < self.nparams { self.params[i] } else { 0 };
            match p {
                0 => {
                    self.fg = DEFAULT_FG;
                    self.bg = DEFAULT_BG;
                    self.bold = false;
                    self.reverse = false;
                    self.underline = false;
                }
                1 => self.bold = true,
                22 => self.bold = false,
                4 => self.underline = true,
                24 => self.underline = false,
                // 2 dim, 5 blink, 10/11 fonts: accepted, not shown.
                7 => self.reverse = true,
                27 => self.reverse = false,
                30..=37 => self.fg = (p - 30) as u8,
                39 => self.fg = DEFAULT_FG,
                40..=47 => self.bg = (p - 40) as u8,
                49 => self.bg = DEFAULT_BG,
                90..=97 => self.fg = (p - 90 + 8) as u8,
                100..=107 => self.bg = (p - 100 + 8) as u8,
                _ => {}
            }
        }
    }

    fn csi(&mut self, final_byte: u8) {
        let n = self.param(0, 1);
        let (col, row) = (self.col.min(self.cols - 1), self.row);
        match final_byte {
            b'A' => self.move_to(col, row.saturating_sub(n)),
            b'B' => self.move_to(col, row + n),
            b'C' => self.move_to(col + n, row),
            b'D' => self.move_to(col.saturating_sub(n), row),
            b'E' => self.move_to(0, row + n),
            b'F' => self.move_to(0, row.saturating_sub(n)),
            b'G' => self.move_to(n - 1, row),
            b'd' => self.move_to(col, n - 1),
            b'H' | b'f' => self.move_to(self.param(1, 1) - 1, n - 1),
            b'J' => match self.param(0, 0) {
                0 => {
                    self.erase(row, col, self.cols);
                    for r in row + 1..self.rows {
                        self.erase(r, 0, self.cols);
                    }
                }
                1 => {
                    for r in 0..row {
                        self.erase(r, 0, self.cols);
                    }
                    self.erase(row, 0, col + 1);
                }
                _ => {
                    for r in 0..self.rows {
                        self.erase(r, 0, self.cols);
                    }
                }
            },
            b'K' => match self.param(0, 0) {
                0 => self.erase(row, col, self.cols),
                1 => self.erase(row, 0, col + 1),
                _ => self.erase(row, 0, self.cols),
            },
            b'X' => self.erase(row, col, col + n),
            b'P' => {
                for c in col..self.cols {
                    let src = if c + n < self.cols { self.cells[row][c + n] } else { self.blank() };
                    self.set_cell(c, row, src);
                }
            }
            b'@' => {
                for c in (col..self.cols).rev() {
                    let src = if c >= col + n { self.cells[row][c - n] } else { self.blank() };
                    self.set_cell(c, row, src);
                }
            }
            b'm' => self.sgr(),
            b'n' if self.param(0, 0) == 6 => {
                let mut buf = [0u8; 24];
                let mut w = Cursor { buf: &mut buf, len: 0 };
                let _ = fmt::write(&mut w, format_args!("\x1b[{};{}R", row + 1, col + 1));
                let len = w.len;
                self.push_reply(&buf[..len]);
            }
            b'n' if self.param(0, 0) == 5 => self.push_reply(b"\x1b[0n"),
            b'h' | b'l' if self.private && self.param(0, 0) == 25 => {
                self.cursor_visible = final_byte == b'h';
            }
            b's' => self.saved = (col, row),
            b'u' => self.move_to(self.saved.0, self.saved.1),
            // Scroll region; the cursor goes home.
            b'r' if !self.private => {
                let top = self.param(0, 1) - 1;
                let bottom = self.param(1, self.rows as u16) - 1;
                if top < bottom && bottom < self.rows {
                    self.top = top;
                    self.bottom = bottom;
                } else {
                    self.top = 0;
                    self.bottom = self.rows - 1;
                }
                self.move_to(0, 0);
            }
            // Insert and delete lines: only inside the scroll region.
            b'L' if (self.top..=self.bottom).contains(&row) => self.scroll_down(row, self.bottom, n),
            b'M' if (self.top..=self.bottom).contains(&row) => self.scroll_up(row, self.bottom, n),
            b'S' => self.scroll_up(self.top, self.bottom, n),
            b'T' if !self.private => self.scroll_down(self.top, self.bottom, n),
            b'h' | b'l' if self.private && self.param(0, 0) == 7 => self.autowrap = final_byte == b'h',
            b'h' | b'l' if !self.private && self.param(0, 0) == 4 => self.insert_mode = final_byte == b'h',
            // Device attributes: a VT102, as the Linux console answers.
            b'c' if !self.private && self.param(0, 0) == 0 => self.push_reply(b"\x1b[?6c"),
            _ => {}
        }
    }

    fn reset_palette(&mut self) {
        if self.palette != PALETTE {
            self.palette = PALETTE;
            self.redraw_next = Some(0);
        }
    }

    /// ESC ] P n rr gg bb: palette entry n (hex digits) becomes #rrggbb.
    fn set_palette(&mut self) {
        let hex = |b: u8| (b as char).to_digit(16).unwrap_or(0) as u8;
        let d = self.osc;
        let entry = hex(d[0]) as usize;
        let color = (hex(d[1]) << 4 | hex(d[2]), hex(d[3]) << 4 | hex(d[4]), hex(d[5]) << 4 | hex(d[6]));
        if self.palette[entry] != color {
            self.palette[entry] = color;
            // Start over: rows drawn so far may use the old color.
            self.redraw_next = Some(0);
        }
    }

    fn control(&mut self, b: u8) {
        match b {
            // A line feed keeps the column, as on a VT (and Linux's console
            // without LNM): CR LF is the writer's (the terminal's ONLCR).
            b'\n' | 0x0b | 0x0c => {
                self.wrap_pending = false;
                self.line_feed();
            }
            b'\r' => self.move_to(0, self.row),
            0x08 => self.move_to(self.col.min(self.cols - 1).saturating_sub(1), self.row),
            b'\t' => self.move_to((self.col / 8 + 1) * 8, self.row),
            // Shift out / shift in: G1 / G0.
            0x0e => self.shift_out = true,
            0x0f => self.shift_out = false,
            0x1b => self.parse = Parse::Escape,
            _ => {}
        }
    }

    fn byte(&mut self, b: u8) {
        match self.parse {
            Parse::Escape => {
                self.parse = Parse::Normal;
                match b {
                    b'[' => {
                        self.parse = Parse::Csi;
                        self.params = [0; MAX_PARAMS];
                        self.nparams = 0;
                        self.private = false;
                    }
                    b'7' => self.saved = (self.col, self.row),
                    b'8' => self.move_to(self.saved.0, self.saved.1),
                    b'D' => self.line_feed(),
                    b'E' => {
                        self.col = 0;
                        self.wrap_pending = false;
                        self.line_feed();
                    }
                    b'M' => self.reverse_index(),
                    b'(' => self.parse = Parse::Charset(0),
                    b')' => self.parse = Parse::Charset(1),
                    b']' => {
                        self.parse = Parse::Osc;
                        self.osc_len = 0;
                    }
                    b'c' => {
                        self.fg = DEFAULT_FG;
                        self.bg = DEFAULT_BG;
                        self.top = 0;
                        self.bottom = self.rows - 1;
                        self.g0_graphics = false;
                        self.g1_graphics = true;
                        self.shift_out = false;
                        self.insert_mode = false;
                        self.autowrap = true;
                        self.underline = false;
                        self.reset_palette();
                        self.clear_screen();
                    }
                    _ => {}
                }
            }
            Parse::Charset(g) => {
                self.parse = Parse::Normal;
                let graphics = b == b'0';
                if g == 0 {
                    self.g0_graphics = graphics;
                } else {
                    self.g1_graphics = graphics;
                }
            }
            Parse::Osc => {
                match b {
                    // ESC ] P: a palette entry follows; ESC ] R resets them.
                    b'P' if self.osc_len == 0 => self.parse = Parse::Palette,
                    b'R' if self.osc_len == 0 => {
                        self.parse = Parse::Normal;
                        self.reset_palette();
                    }
                    0x07 => self.parse = Parse::Normal,
                    0x1b => self.parse = Parse::Escape,
                    _ => self.osc_len = 1,
                }
            }
            Parse::Palette => {
                if !(b as char).is_ascii_hexdigit() {
                    self.parse = Parse::Normal;
                } else {
                    self.osc[self.osc_len] = b;
                    self.osc_len += 1;
                    if self.osc_len == self.osc.len() {
                        self.parse = Parse::Normal;
                        self.set_palette();
                    }
                }
            }
            Parse::Csi => match b {
                b'0'..=b'9' => {
                    if self.nparams == 0 {
                        self.nparams = 1;
                    }
                    if let Some(p) = self.params.get_mut(self.nparams - 1) {
                        *p = p.saturating_mul(10).saturating_add((b - b'0') as u16);
                    }
                }
                b';' => self.nparams = (self.nparams.max(1) + 1).min(MAX_PARAMS),
                b'?' => self.private = true,
                0x40..=0x7e => {
                    self.parse = Parse::Normal;
                    self.csi(b);
                }
                _ => {}
            },
            Parse::Normal => self.text_byte(b),
        }
    }

    fn text_byte(&mut self, b: u8) {
        if self.utf8_need > 0 {
            if b & 0xc0 == 0x80 {
                self.utf8[self.utf8_len] = b;
                self.utf8_len += 1;
                if self.utf8_len == self.utf8_need {
                    let ch = core::str::from_utf8(&self.utf8[..self.utf8_len])
                        .ok()
                        .and_then(|s| s.chars().next())
                        .unwrap_or('?');
                    self.utf8_need = 0;
                    self.put_char(ch);
                }
                return;
            }
            self.utf8_need = 0;
            self.put_char('?');
        }
        match b {
            0x00..=0x1f | 0x7f => self.control(b),
            0x20..=0x7e => self.put_char(b as char),
            0xc0..=0xf7 => {
                self.utf8[0] = b;
                self.utf8_len = 1;
                self.utf8_need = match b {
                    0xc0..=0xdf => 2,
                    0xe0..=0xef => 3,
                    _ => 4,
                };
            }
            _ => self.put_char('?'),
        }
    }

    /// Processes bytes (and a pending redraw) until the work budget of one
    /// lock hold is spent; returns how many bytes it consumed. Call again
    /// while bytes or `redraw_pending` remain.
    pub fn write_some(&mut self, bytes: &[u8]) -> usize {
        self.work = 0;
        self.hide_cursor();
        let mut used = 0;
        while self.work < WORK_BUDGET {
            if let Some(row) = self.redraw_next {
                for c in 0..self.cols {
                    self.draw_cell(c, row, false);
                }
                self.redraw_next = (row + 1 < self.rows).then_some(row + 1);
                continue;
            }
            let Some(&b) = bytes.get(used) else { break };
            self.byte(b);
            used += 1;
        }
        self.show_cursor();
        used
    }

    pub fn redraw_pending(&self) -> bool {
        self.redraw_next.is_some()
    }

    /// The kernel's own text (printk): answers to queries in it go nowhere.
    pub fn write_bytes(&mut self, bytes: &[u8]) {
        let mut rest = bytes;
        while !rest.is_empty() || self.redraw_pending() {
            let n = self.write_some(rest);
            self.reply_len = 0;
            rest = &rest[n..];
        }
    }
}

/// Minimal `fmt::Write` sink over a fixed buffer.
struct Cursor<'a> {
    buf: &'a mut [u8],
    len: usize,
}

impl fmt::Write for Cursor<'_> {
    fn write_str(&mut self, s: &str) -> fmt::Result {
        let n = s.len().min(self.buf.len() - self.len);
        self.buf[self.len..self.len + n].copy_from_slice(&s.as_bytes()[..n]);
        self.len += n;
        Ok(())
    }
}

/// The kernel's own text to a byte sink: a newline is a carriage return and a
/// line feed (the devices take bytes as they are; this is the kernel's ONLCR).
struct Text<F: FnMut(&[u8])>(F);

impl<F: FnMut(&[u8])> fmt::Write for Text<F> {
    fn write_str(&mut self, s: &str) -> fmt::Result {
        for (i, part) in s.split('\n').enumerate() {
            if i > 0 {
                (self.0)(b"\r\n");
            }
            (self.0)(part.as_bytes());
        }
        Ok(())
    }
}

pub static CONSOLE: IrqSpinLock<Option<Console>> = IrqSpinLock::new(None);

pub fn init(fb: &'static mut FrameBuffer) {
    let info = fb.info();
    let mut console = Console {
        fb: fb.buffer_mut(),
        info,
        cells: unsafe { &mut *(&raw mut CELLS) },
        cols: (info.width / CHAR_WIDTH).min(MAX_COLS),
        rows: (info.height / LINE_HEIGHT).min(MAX_ROWS),
        col: 0,
        row: 0,
        wrap_pending: false,
        fg: DEFAULT_FG,
        bg: DEFAULT_BG,
        bold: false,
        reverse: false,
        saved: (0, 0),
        cursor_visible: true,
        cursor_drawn: None,
        parse: Parse::Normal,
        params: [0; MAX_PARAMS],
        nparams: 0,
        private: false,
        utf8: [0; 4],
        utf8_len: 0,
        utf8_need: 0,
        reply: [0; REPLY_CAP],
        reply_len: 0,
        top: 0,
        bottom: 0,
        g0_graphics: false,
        g1_graphics: true,
        shift_out: false,
        underline: false,
        insert_mode: false,
        autowrap: true,
        palette: PALETTE,
        osc: [0; 7],
        osc_len: 0,
        redraw_next: None,
        work: 0,
    };
    console.bottom = console.rows - 1;
    console.fb.fill(0);
    console.clear_screen();
    console.draw_logo();
    *CONSOLE.lock() = Some(console);
}

#[macro_export]
macro_rules! printk {
    ($($arg:tt)*) => ($crate::drivers::console::_print(format_args!($($arg)*)));
}

#[macro_export]
macro_rules! printkln {
    () => ($crate::printk!("\n"));
    ($($arg:tt)*) => ($crate::printk!("{}\n", format_args!($($arg)*)));
}

pub fn _print(args: fmt::Arguments) {
    use core::fmt::Write;
    let _ = Text(super::serial::write_bytes).write_fmt(args);
    without_interrupts(|| {
        if let Some(c) = CONSOLE.lock().as_mut() {
            let _ = Text(|b: &[u8]| c.write_bytes(b)).write_fmt(args);
        }
    });
}

/// Writes text of the kernel's (the monitor's echo, the native servers' output):
/// newlines become CR LF.
pub fn write_text(bytes: &[u8]) {
    for (i, part) in bytes.split(|&b| b == b'\n').enumerate() {
        if i > 0 {
            write_bytes(b"\r\n");
        }
        write_bytes(part);
    }
}

/// Bytes per serial-port lock hold (it waits for the UART with interrupts
/// off).
const SERIAL_CHUNK: usize = 256;

/// Writes to the serial mirror and the screen. The screen is drawn in
/// budgeted pieces (`Console::write_some`), releasing the lock and
/// interrupts in between, so other CPUs and interrupt handlers never wait
/// long for the console. Between pieces a task that is due takes over the
/// CPU: a write that redraws the whole screen takes long, and the kernel
/// does not preempt itself.
pub fn write_bytes(bytes: &[u8]) {
    write_with_replies(bytes, &mut |_| {});
}

/// `write_bytes`, handing the console's answers to queries in `bytes` (a cursor
/// position report, device attributes) to `replies`: taken in the same lock hold that
/// made them, so they are this write's and none is lost.
pub fn write_with_replies(bytes: &[u8], replies: &mut dyn FnMut(&[u8])) {
    for chunk in bytes.chunks(SERIAL_CHUNK) {
        super::serial::write_bytes(chunk);
    }
    let mut rest = bytes;
    loop {
        let mut reply = [0u8; REPLY_CAP];
        let (used, pending, n) = match CONSOLE.lock().as_mut() {
            Some(c) => {
                let used = c.write_some(rest);
                let n = c.reply_len;
                reply[..n].copy_from_slice(&c.reply[..n]);
                c.reply_len = 0;
                (used, c.redraw_pending(), n)
            }
            None => return,
        };
        if n > 0 {
            replies(&reply[..n]);
        }
        rest = &rest[used..];
        if rest.is_empty() && !pending {
            return;
        }
        crate::process::sched::cond_resched();
    }
}

/// (columns, rows)
pub fn size() -> (usize, usize) {
    without_interrupts(|| CONSOLE.lock().as_ref().map_or((80, 25), |c| (c.cols, c.rows)))
}

pub fn clear_screen() {
    without_interrupts(|| {
        if let Some(c) = CONSOLE.lock().as_mut() {
            c.hide_cursor();
            c.clear_screen();
            c.show_cursor();
        }
    });
}
