#!/usr/bin/env python3
"""Generates docs/codemap.md: every source file with its size and the first
sentence of its module comment, the public types of each Rust file, the
kernel ABI of the Linux server (crates/restricted) with the file that
handles each call, and the documents under docs/.

The map lets a reader (or an agent) find the file for a task without
reading the tree. `--check` fails if docs/codemap.md is out of date (CI).

Usage: scripts/codemap.py [--check]
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "codemap.md"

# Areas in the order the map lists them: (title, path prefix).
AREAS = [
    ("Kernel", "kernel/src/"),
    ("Linux server", "servers/linux/"),
    ("Other servers", "servers/"),
    ("Libraries", "crates/"),
    ("Host builder", "builder/"),
    ("User-space programs and tests", "userspace/"),
    ("Scripts", "scripts/"),
]

SOURCE = re.compile(r"\.(rs|c|h|sh|py)$")
PUB_TYPE = re.compile(r"^pub(?:\([a-z]+\))? (?:unsafe )?(struct|enum|trait|union) ([A-Za-z_][A-Za-z0-9_]*)")
ABI_CONST = re.compile(r"^pub const (SYS_[A-Z0-9_]+): u64 = (\d+);")
SUMMARY_LEN = 220


def tracked_files():
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True).stdout
    return [p for p in out.splitlines() if (ROOT / p).is_file()]


def first_sentence(text):
    text = " ".join(text.split())
    m = re.search(r"(.+?[.!?])(\s|$)", text)
    s = m.group(1) if m else text
    if len(s) > SUMMARY_LEN:
        s = s[: SUMMARY_LEN - 3].rsplit(" ", 1)[0] + "..."
    return s


def summary(path, lines):
    """The first sentence of the file's leading comment."""
    if path.endswith(".rs"):
        doc = []
        for line in lines:
            s = line.strip()
            if s.startswith("//!"):
                doc.append(s[3:])
            elif doc or (s and not s.startswith("#!") and not s.startswith("//")):
                break
        return first_sentence(" ".join(doc)) if doc else ""
    if path.endswith((".c", ".h")):
        text = "\n".join(lines[:40])
        m = re.match(r"\s*/\*(.*?)\*/", text, re.S)
        if not m:
            return ""
        return first_sentence(re.sub(r"^\s*\*", "", m.group(1), flags=re.M))
    if path.endswith((".sh", ".py")):
        doc = []
        body = lines[1:] if lines and lines[0].startswith("#!") else lines
        if path.endswith(".py") and body and body[0].startswith('"""'):
            text = "\n".join(body)
            m = re.match(r'"""(.*?)"""', text, re.S)
            return first_sentence(m.group(1)) if m else ""
        for line in body:
            if line.startswith("#"):
                doc.append(line.lstrip("#"))
            elif doc or line.strip():
                break
        return first_sentence(" ".join(doc)) if doc else ""
    return ""


def code_lines(lines):
    """Lines that are neither blank nor comments (roughly)."""
    return sum(1 for l in lines if l.strip() and not l.strip().startswith(("//", "/*", "*", "#")))


def area_of(path):
    for title, prefix in AREAS:
        if path.startswith(prefix):
            return title
    return None


def abi_table(files, texts):
    consts = []
    for line in texts.get("crates/restricted/src/lib.rs", []):
        m = ABI_CONST.match(line)
        if m:
            consts.append((m.group(1), int(m.group(2))))
    rows = []
    kernel = [p for p in files if p.startswith("kernel/src/") and p.endswith(".rs")]
    for name, num in consts:
        arm = re.compile(r"\b" + name + r"\b.*=>")
        where = []
        for p in kernel:
            for i, line in enumerate(texts[p], 1):
                if arm.search(line):
                    where.append(f"{p}:{i}")
        rows.append((num, name, ", ".join(where) or "-"))
    return sorted(rows)


def main():
    check = "--check" in sys.argv[1:]
    files = sorted(tracked_files())
    texts = {}
    for p in files:
        if SOURCE.search(p):
            texts[p] = (ROOT / p).read_text(errors="replace").splitlines()

    out = [
        "# Code map",
        "",
        "Generated by `scripts/codemap.py` from the tracked sources; do not edit by hand. Regenerate",
        "with `python3 scripts/codemap.py` after adding, removing or re-documenting files (CI checks",
        "that it is current). Each line: path, lines of code, the first sentence of the file's",
        "module comment, and the public types it defines. Where to start for common tasks: CLAUDE.md,",
        "\"Finding code\".",
    ]
    for title, _ in AREAS:
        entries = [p for p in files if p in texts and area_of(p) == title and "/rootfs/" not in p]
        if not entries:
            continue
        out += ["", f"## {title}", ""]
        for p in entries:
            lines = texts[p]
            line = f"- `{p}` ({code_lines(lines)})"
            s = summary(p, lines)
            if s:
                line += f" {s}"
            if p.endswith(".rs"):
                types = [m.group(2) for l in lines if (m := PUB_TYPE.match(l.strip()))]
                if types:
                    line += " Types: " + ", ".join(f"`{t}`" for t in types) + "."
            out.append(line)

    scripts = [p for p in files if p.startswith("userspace/rootfs/") and p in texts]
    if scripts:
        out += ["", "## Root filesystem scripts", ""]
        for p in scripts:
            s = summary(p, texts[p])
            out.append(f"- `{p}`" + (f" {s}" if s else ""))

    out += [
        "",
        "## Kernel ABI of the Linux server",
        "",
        "The calls in `crates/restricted/src/lib.rs` (documented there) and the match arms in the",
        "kernel that handle them.",
        "",
        "| nr | call | handled at |",
        "|---|---|---|",
    ]
    for num, name, where in abi_table(files, texts):
        out.append(f"| {num} | `{name}` | {where} |")

    docs = [p for p in files if p.startswith("docs/") and p.endswith(".md") and p != "docs/codemap.md"]
    out += ["", "## Documents", ""]
    for p in docs:
        heading = next((l.lstrip("# ").strip() for l in (ROOT / p).read_text().splitlines() if l.startswith("#")), "")
        out.append(f"- `{p}` {heading}")

    text = "\n".join(out) + "\n"
    if check:
        if not OUT.exists() or OUT.read_text() != text:
            print("docs/codemap.md is out of date: run python3 scripts/codemap.py", file=sys.stderr)
            sys.exit(1)
        return
    OUT.write_text(text)


if __name__ == "__main__":
    main()
