[package]
name = "procfs"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[[bin]]
name = "procfs"
test = false
bench = false

[dependencies]
oxrt = { path = "../../crates/oxrt" }
procproto = { path = "../../crates/procproto" }
ring = { path = "../../crates/ring" }
fsring = { path = "../../crates/fsring" }
